Removing direct calls to $
Please do not call directly jquery with $. 
Jquery is not loaded in the client by meteor before everything else... 

These $ calls caused the following error in my app:
Uncaught TypeError: $ is not a functionTemplate.Mongol_docControls.events.click .Mongol_m_right @ docControls.js:114(anonymous function) @ template.js:463Template._withTemplateInstanceFunc @ template.js:437

Jquery is officially available only in Template instances through TemplateInstance.$

I also fixed someplace where you used $.map. 
Same thing, jquery in meteor for utility calls is not wise. 
As Underscore.js is available in all your Meteor app, it is better to use _.map.

I have not looked elsewhere in your app, but i am pretty sure this pattern can cause other bugs !